// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FileUpload() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container\"><div class=\"header\"><h1>Memory Leak Analyzer</h1><p>Upload a Go memory profile file to analyze memory leaks and visualize data</p></div><div class=\"card\"><h2>Upload Memory Profile</h2><form action=\"/upload\" method=\"post\" enctype=\"multipart/form-data\"><div class=\"upload-area\"><div style=\"margin-bottom: 1rem;\"><svg width=\"48\" height=\"48\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" style=\"margin: 0 auto; display: block; color: #94a3b8;\"><path d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"></path> <polyline points=\"14,2 14,8 20,8\"></polyline> <line x1=\"16\" y1=\"13\" x2=\"8\" y2=\"13\"></line> <line x1=\"16\" y1=\"17\" x2=\"8\" y2=\"17\"></line> <polyline points=\"10,9 9,9 8,9\"></polyline></svg></div><h3 style=\"margin-bottom: 0.5rem; color: #374151;\">Choose a memory profile file</h3><p style=\"margin-bottom: 1.5rem; color: #64748b;\">Select a Go memory profile file (.txt, .prof, or any text file)</p><input type=\"file\" name=\"file\" accept=\".txt,.prof,text/*\" required style=\"margin-bottom: 1rem;\"><br><button type=\"submit\" class=\"btn\">Upload and Analyze</button></div></form></div><div class=\"card\"><h2>Sample Data</h2><p style=\"margin-bottom: 1rem;\">You can also view a sample analysis with pre-loaded data:</p><a href=\"/sample\" class=\"btn\">View Sample Analysis</a></div><div class=\"card\"><h2>How to Generate Memory Profiles</h2><p style=\"margin-bottom: 1rem;\">To generate a memory profile in your Go application:</p><div style=\"background: #f1f5f9; padding: 1rem; border-radius: 8px; overflow-x: auto; font-size: 0.875rem; font-family: monospace;\">1. Import pprof in your application<br>2. Add HTTP server for pprof<br>3. Use go tool pprof to generate profile<br>4. Export as text and upload here</div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Memory Leak Analyzer").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
